export const ITEM_PER_PAGE = 10;

type RouteAccessMap = {
  [key: string]: string[];
};

export const routeAccessMap: RouteAccessMap = {
  "/admin(.*)": ["admin"],
  "/student(.*)": ["student"],
  "/teacher(.*)": ["teacher"],
  "/parent(.*)": ["parent"],
  "/list/teachers": ["admin", "teacher", "parent"],
  "/list/students": ["admin", "teacher"],
  "/list/parents": ["admin", "teacher"],
  "/list/subjects": ["admin", "teacher", "parent"],
  "/list/classes": ["admin", "teacher", "parent"],
  "/list/lessons": ["admin", "teacher", "student", "parent"],
  "/list/exams": ["admin", "teacher", "student", "parent"],
  "/list/assignments": ["admin", "teacher", "student", "parent"],
  "/list/results": ["admin", "teacher", "student", "parent"],
  "/list/attendance": ["admin", "teacher", "student", "parent"],
  "/list/events": ["admin", "teacher", "student", "parent"],
  "/list/announcements": ["admin", "teacher", "student", "parent"],
  // "/settings": ["admin", "teacher", "student", "parent"],
  "/list/approvements": ["admin"],
};
export const subjectData = [
  { id: "Ban-1", name: "Bangla-1" },
  { id: "Ban-2", name: "Bangla-2" },
  { id: "Eng-1", name: "English-1" },
  { id: "Eng-2", name: "English-2" },
  { id: "Math", name: "Mathematics" },
  { id: "GenSci", name: "General Science" },
  { id: "BGS", name: "Bangladesh and Global Studies" },
  { id: "ICT", name: "Information and Communication Technology" },
  { id: "Rel", name: "Religion (Islamic Studies or Hindu Studies)" },
  { id: "Phy", name: "Physics" },
  { id: "Bio", name: "Biology" },
  { id: "HM", name: "Home Management" },
  { id: "Acc", name: "Accounting" },
  { id: "BOM", name: "Business Organization and Management" },
  { id: "Eco", name: "Economics" },
  { id: "Stat", name: "Statistics" },
  { id: "Hist", name: "History" },
  { id: "Civ", name: "Civics and Good Citizenship" },
  { id: "IHC", name: "Islamic History and Culture" },
  { id: "Phy-1", name: "Physics-1" },
  { id: "Chem-1", name: "Chemistry-1" },
  { id: "Bio-1", name: "Biology-1" },
  { id: "HM-1", name: "Home Management-1" },
  { id: "Acc-1", name: "Accounting-1" },
  { id: "BOM-1", name: "Business Organization and Management-1" },
  { id: "Eco-1", name: "Economics-1" },
  { id: "Hist-1", name: "History-1" },
  { id: "Civ-1", name: "Civics-1" },
  { id: "IHC-1", name: "Islamic History and Culture-1" },
  { id: "Phy-2", name: "Physics-2" },
  { id: "Chem-2", name: "Chemistry-2" },
  { id: "Bio-2", name: "Biology-2" },
  { id: "HM-2", name: "Home Management-2" },
  { id: "Acc-2", name: "Accounting-2" },
  { id: "BOM-2", name: "Business Organization and Management-2" },
  { id: "Eco-2", name: "Economics-2" },
  { id: "Hist-2", name: "History-2" },
  { id: "Civ-2", name: "Civics-2" },
  { id: "IHC-2", name: "Islamic History and Culture-2" },
];

export const classNames = [
  { key: "class7", label: "Class 7" },
  { key: "class8", label: "Class 8" },
  { key: "class9-sci", label: "Class 9 Science" },
  { key: "class9-art", label: "Class 9 Arts" },
  { key: "class9-com", label: "Class 9 Commerce" },
  { key: "class10-sci", label: "Class 10 Science" },
  { key: "class10-art", label: "Class 10 Arts" },
  { key: "class10-com", label: "Class 10 Commerce" },
  { key: "class11-sci", label: "Class 11 Science" },
  { key: "class11-art", label: "Class 11 Arts" },
  { key: "class11-com", label: "Class 11 Commerce" },
  { key: "class12-sci", label: "Class 12 Science" },
  { key: "class12-art", label: "Class 12 Arts" },
  { key: "class12-com", label: "Class 12 Commerce" },
];
